"""Contract tests for LLM-AC-01-INFERENCE rows in the rubric matrix.

Generated by scripts/generate_phase2_requirement_tests.py from
docs/phase2/rubric-matrix.csv — do not hand-edit; regenerate instead.

Import-light by design: parses evidence markdown and checks the declared
artifact_path exists, without importing feast/torch/mlflow or any service
dependency. The phase-08 auditor runs each row's validation_command as its
own subprocess across 60 rows; a slow import here multiplies 60x. Row data
(evidence_path, artifact_repo, artifact_path) is looked up from `MATRIX` at
test time rather than baked in here, so this file never drifts from the CSV.
"""

from __future__ import annotations

import pytest

from .conftest import (
    EVIDENCE_REQUIRED_KEYS,
    GITOPS_ROOT,
    MATRIX,
    REPO_ROOT,
    parse_evidence_fields,
)

RUBRIC_IDS = [
    "LLM-a-llm-inference-platform--a-custom-model",
    "LLM-a-llm-inference-platform--benchmark-model-server-and-opt",
    "LLM-a-llm-inference-platform--llm-inference-platform-setup-c",
]


@pytest.mark.parametrize("rubric_id", RUBRIC_IDS)
def test_requirement_evidence_contract(rubric_id: str) -> None:
    """Evidence file, contract fields, and implementation artifact all exist.

    Skips (never fails) while the row is still design_only — this file is
    generated on day 1, long before the row is executed. A missing evidence
    file at phase-08 promotion time is instead caught by
    scripts/audit_phase2_evidence.py --require-executed, which does not skip.
    """
    row = MATRIX[rubric_id]
    evidence_path = REPO_ROOT / row["evidence_path"]
    if not evidence_path.exists():
        pytest.skip(f"evidence not yet executed: {row['evidence_path']}")

    text = evidence_path.read_text(encoding="utf-8", errors="replace")
    assert (
        rubric_id in text
    ), f"evidence file {row['evidence_path']} does not reference its rubric_id"

    fields = parse_evidence_fields(text)
    missing = [k for k in EVIDENCE_REQUIRED_KEYS if not fields.get(k)]
    assert not missing, f"{rubric_id}: evidence file missing/empty metadata keys: {missing}"

    if row["artifact_repo"] == "gitops":
        if GITOPS_ROOT is None or not GITOPS_ROOT.is_dir():
            pytest.skip(
                "gitops checkout not available: set PHASE2_GITOPS_ROOT to the "
                "financial-distress-gitops working copy"
            )
        root = GITOPS_ROOT
    else:
        root = REPO_ROOT
    artifact = root / row["artifact_path"]
    assert artifact.is_file(), f"{rubric_id}: implementation artifact not found: {artifact}"
