apiVersion: batch/v1
kind: CronJob
metadata:
  name: stream-feature-offline
  namespace: agents-sandbox
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: stream-feature-offline
              image: ghcr.io/emanhthangngot/financial-distress-data/stream-feature-offline:dev
              imagePullPolicy: IfNotPresent
              envFrom:
                - secretRef:
                    name: platform-streaming
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: stream-feature-online
  namespace: agents-sandbox
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: stream-feature-online
              image: ghcr.io/emanhthangngot/financial-distress-data/stream-feature-online:dev
              imagePullPolicy: IfNotPresent
              envFrom:
                - secretRef:
                    name: platform-streaming
