FROM apache/airflow:2.10.5-python3.11

USER root
RUN apt-get update && apt-get install -y graphviz openjdk-17-jre-headless

USER airflow
RUN python -m pip install \
    duckdb==1.1.3 \
    kafka-python==2.0.2 \
    minio==7.2.12 \
    pyarrow==17.0.0 \
    "psycopg[binary]==3.2.3" \
    pyspark==3.5.6
