"""platform rubric coverage audit runner (W25).

Walks the shared item catalogue in ``scripts/_rubric_items.py``, runs each
``evidence_check`` callback, and writes a machine-readable summary to
``docs/evidence/rubric_coverage.json``. Also prints a human-readable table.

Run:
    .venv/bin/python scripts/audit_rubric_coverage.py

Status:
    covered  - at least one evidence file exists
    partial  - 0 evidence but item is known runtime-only / xfail in pytest
    missing  - 0 evidence and not in the partial whitelist
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import UTC, datetime
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT))

from scripts._rubric_items import ITEMS, total_points  # noqa: E402

EVIDENCE = PROJECT_ROOT / "docs" / "evidence"
OUTPUT_PATH = EVIDENCE / "rubric_coverage.json"

# Items whose evidence is runtime-only (regenerated by run_stage1_* scripts).
# These are marked 'partial' instead of 'missing' when their files are absent.
RUNTIME_ONLY_IDXS: frozenset[int] = frozenset({3, 4})


def status_for(idx: int, evidence: list[str]) -> str:
    if evidence:
        return "covered"
    if idx in RUNTIME_ONLY_IDXS:
        return "partial"
    return "missing"


def build_report() -> dict:
    items_out: list[dict] = []
    covered_pts = 0
    partial_pts = 0
    missing_pts = 0
    for item in ITEMS:
        evidence = item.evidence_check()
        status = status_for(item.idx, evidence)
        if item.points > 0:
            if status == "covered":
                covered_pts += item.points
            elif status == "partial":
                partial_pts += item.points
            else:
                missing_pts += item.points
        items_out.append(
            {
                "idx": item.idx,
                "category": item.category,
                "claim": item.claim,
                "points": item.points,
                "status": status,
                "evidence": evidence,
            }
        )
    total = total_points()
    return {
        "generated_at": datetime.now(UTC).isoformat(),
        "rubric_total": total,
        "covered_points": covered_pts,
        "partial_points": partial_pts,
        "missing_points": missing_pts,
        "coverage_pct": round(100.0 * covered_pts / total, 2) if total else 0.0,
        "items": items_out,
    }


def print_summary(report: dict) -> None:
    print(
        f"Rubric total: {report['rubric_total']} pts  |  "
        f"covered: {report['covered_points']}  "
        f"partial: {report['partial_points']}  "
        f"missing: {report['missing_points']}  "
        f"({report['coverage_pct']}%)"
    )
    print()
    by_cat: dict[str, list[dict]] = {}
    for it in report["items"]:
        by_cat.setdefault(it["category"], []).append(it)
    for cat, items in by_cat.items():
        c = sum(i["points"] for i in items if i["status"] == "covered" and i["points"] > 0)
        t = sum(i["points"] for i in items)
        print(f"== {cat} ({c}/{t} pts) ==")
        for i in items:
            mark = {"covered": "[x]", "partial": "[~]", "missing": "[ ]"}[i["status"]]
            if i["points"] == 0:
                print(f"  {mark} idx {i['idx']:>2}  (sum row)")
            else:
                print(f"  {mark} idx {i['idx']:>2}  {i['points']:>2}pt  {i['claim'][:70]}")
        print()


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--out",
        type=Path,
        default=OUTPUT_PATH,
        help="Output JSON path (default: docs/evidence/rubric_coverage.json)",
    )
    parser.add_argument(
        "--quiet",
        action="store_true",
        help="Suppress the printed summary table",
    )
    args = parser.parse_args()
    report = build_report()
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(json.dumps(report, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    if not args.quiet:
        print_summary(report)
    print(f"Wrote: {args.out.relative_to(PROJECT_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
