#!/usr/bin/env python3
"""Regenerate docs/platform/rubric-matrix.{csv,md} from the source of truth.

Run:  python scripts/generate_platform_matrix.py
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

from scripts._platform_rubric_items import ITEMS, export_matrix_csv  # noqa: E402

DOCS = REPO_ROOT / "docs" / "phase2"


def main() -> int:
    DOCS.mkdir(parents=True, exist_ok=True)

    # CSV
    csv_path = DOCS / "rubric-matrix.csv"
    csv_path.write_text(export_matrix_csv(), encoding="utf-8")

    # Markdown
    lines: list[str] = []
    lines.append("# platform .ubric Matrix (200 points)")
    lines.append("")
    lines.append(
        "Machine-readable source: `docs/platform/rubric-matrix.csv`, regenerated by "
        "`scripts/generate_platform_matrix.py` from `scripts/_platform_rubric_items.py`."
    )
    lines.append("")
    ml_pts = sum(i.points for i in ITEMS if i.track == "ML")
    llm_pts = sum(i.points for i in ITEMS if i.track == "LLM")
    lines.append(f"Totals: **ML {ml_pts} pts**, **LLM {llm_pts} pts**.")
    lines.append("")
    cols = (
        "rubric_id | Track | Section | Pts | Requirement | Owner "
        "| Acceptance | Behavior validation | Evidence path | Artifact"
    )
    header = f"| {cols} |"
    lines.append(header)
    lines.append("|---|---|---|---|---|---|---|---|---|---|")
    for item in sorted(ITEMS, key=lambda i: (i.track, i.rubric_id)):
        req = item.requirement.replace("\n", " ")[:80].replace("|", "/")
        section = item.section.replace("\n", " ")[:40].replace("|", "/")
        validation = item.validation_command.replace("|", "/")
        lines.append(
            f"| {item.rubric_id} | {item.track} | {section} | {item.points} | "
            f"{req} | {item.owner} | {item.acceptance_id} | `{validation}` | "
            f"{item.evidence_path} | {item.artifact_repo}:{item.artifact_path} |"
        )
    (DOCS / "rubric-matrix.md").write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"Wrote {csv_path}")
    print(f"Wrote {DOCS / 'rubric-matrix.md'} ({len(lines)} lines)")
    print(f"ML={ml_pts} pts, LLM={llm_pts} pts, items={len(ITEMS)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
