#!/usr/bin/env python3
"""Generate the LLM-track requirement contract tests from the rubric matrix.

Reads `docs/phase2/rubric-matrix.csv`, groups the 60 LLM rows by the target
file named in their `validation_command`, and (re)writes one parametrized,
import-light test file per acceptance ID under `tests/phase2/requirements/`.
Each row becomes one parametrized test case whose node id is the row's exact
`rubric_id`, so `pytest tests/phase2/requirements/test_X.py -k '<rubric_id>'`
— the validation_command every matrix row carries — always selects exactly
one case.

Usage:
  python scripts/generate_phase2_requirement_tests.py          # write files
  python scripts/generate_phase2_requirement_tests.py --check  # exit 1 if stale

Regenerate after editing rubric-matrix.csv's LLM rows; do not hand-edit the
generated files, they are overwritten on the next run.
"""

from __future__ import annotations

import argparse
import csv
import re
import sys
from pathlib import Path

from black import FileMode, TargetVersion, format_str

REPO_ROOT = Path(__file__).resolve().parents[1]
# Matches pyproject.toml [tool.black]; kept in sync manually since black has
# no public API to read a project's config file.
BLACK_MODE = FileMode(line_length=100, target_versions={TargetVersion.PY311})
MATRIX_PATH = REPO_ROOT / "docs" / "phase2" / "rubric-matrix.csv"
OUT_DIR = REPO_ROOT / "tests" / "phase2" / "requirements"

FILENAME_RE = re.compile(r"test_[a-z0-9_]+\.py")

HEADER_TEMPLATE = '''"""Contract tests for {acceptance_id} rows in the rubric matrix.

Generated by scripts/generate_phase2_requirement_tests.py from
docs/phase2/rubric-matrix.csv — do not hand-edit; regenerate instead.

Import-light by design: parses evidence markdown and checks the declared
artifact_path exists, without importing feast/torch/mlflow or any service
dependency. The phase-08 auditor runs each row's validation_command as its
own subprocess across 60 rows; a slow import here multiplies 60x. Row data
(evidence_path, artifact_repo, artifact_path) is looked up from `MATRIX` at
test time rather than baked in here, so this file never drifts from the CSV.
"""

from __future__ import annotations

import pytest

from .conftest import (
    EVIDENCE_REQUIRED_KEYS,
    GITOPS_ROOT,
    MATRIX,
    REPO_ROOT,
    parse_evidence_fields,
)

RUBRIC_IDS = {rubric_ids!r}


@pytest.mark.parametrize("rubric_id", RUBRIC_IDS)
def test_requirement_evidence_contract(rubric_id: str) -> None:
    """Evidence file, contract fields, and implementation artifact all exist.

    Skips (never fails) while the row is still design_only — this file is
    generated on day 1, long before the row is executed. A missing evidence
    file at phase-08 promotion time is instead caught by
    scripts/audit_phase2_evidence.py --require-executed, which does not skip.
    """
    row = MATRIX[rubric_id]
    evidence_path = REPO_ROOT / row["evidence_path"]
    if not evidence_path.exists():
        pytest.skip(f"evidence not yet executed: {{row['evidence_path']}}")

    text = evidence_path.read_text(encoding="utf-8", errors="replace")
    assert rubric_id in text, (
        f"evidence file {{row['evidence_path']}} does not reference its rubric_id"
    )

    fields = parse_evidence_fields(text)
    missing = [k for k in EVIDENCE_REQUIRED_KEYS if not fields.get(k)]
    assert not missing, f"{{rubric_id}}: evidence file missing/empty metadata keys: {{missing}}"

    if row["artifact_repo"] == "gitops":
        if GITOPS_ROOT is None or not GITOPS_ROOT.is_dir():
            pytest.skip(
                "gitops checkout not available: set PHASE2_GITOPS_ROOT to the "
                "financial-distress-gitops working copy"
            )
        root = GITOPS_ROOT
    else:
        root = REPO_ROOT
    artifact = root / row["artifact_path"]
    assert artifact.is_file(), f"{{rubric_id}}: implementation artifact not found: {{artifact}}"
'''

CONFTEST_CONTENT = '''"""Shared parsing helpers and matrix lookup for the requirement tests.

Mirrors `_parse_evidence_fields`/`EVIDENCE_REQUIRED_KEYS` in
scripts/audit_phase2_evidence.py (duplicated, not imported, to keep these
tests import-light — the auditor script itself is not a service dependency,
but importing it pulls in argparse/subprocess wiring these 60 subprocess
invocations don't need).
"""

from __future__ import annotations

import csv
import os
import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
# Mirrors the auditor's --gitops-root: no baked assumption about a sibling
# checkout. PHASE2_GITOPS_ROOT overrides; unset, GITOPS_ROOT is None and every
# gitops-artifact case skips with an explicit "not checked out" reason instead
# of misreporting a missing checkout as a missing implementation artifact.
_gitops_env = os.environ.get("PHASE2_GITOPS_ROOT")
GITOPS_ROOT = Path(_gitops_env) if _gitops_env else None
MATRIX_PATH = REPO_ROOT / "docs" / "phase2" / "rubric-matrix.csv"

EVIDENCE_REQUIRED_KEYS = [
    "rubric_id",
    "execution_timestamp",
    "source_sha",
    "gitops_sha",
    "versions",
    "command",
    "expected_result",
    "actual_result",
    "redaction_status",
]


def _load_matrix() -> dict[str, dict[str, str]]:
    """rubric_id -> row, read fresh from the CSV so tests never bake stale data."""
    rows = csv.DictReader(MATRIX_PATH.read_text(encoding="utf-8").splitlines())
    return {row["rubric_id"]: row for row in rows}


MATRIX = _load_matrix()


def parse_evidence_fields(text: str) -> dict[str, str]:
    """Extract ``key: value`` metadata pairs from an evidence markdown file."""
    fields: dict[str, str] = {}
    for line in text.splitlines():
        stripped = line.strip()
        match = re.match(r"^[-*]?\\s*\\**([a-z_]+)\\**\\s*:\\s*(.*)$", stripped, re.IGNORECASE)
        if not match:
            continue
        key = match.group(1).strip().lower()
        if key in EVIDENCE_REQUIRED_KEYS:
            fields[key] = match.group(2).strip()
    return fields
'''


def _read_llm_rows() -> list[dict[str, str]]:
    rows = list(csv.DictReader(MATRIX_PATH.read_text(encoding="utf-8").splitlines()))
    return [r for r in rows if r.get("track") == "LLM"]


def _group_by_file(rows: list[dict[str, str]]) -> dict[str, list[dict[str, str]]]:
    grouped: dict[str, list[dict[str, str]]] = {}
    for row in rows:
        match = FILENAME_RE.search(row["validation_command"])
        if not match:
            raise ValueError(
                f"{row['rubric_id']}: cannot parse target filename from "
                f"validation_command {row['validation_command']!r}"
            )
        grouped.setdefault(match.group(0), []).append(
            {"rubric_id": row["rubric_id"], "acceptance_id": row["acceptance_id"]}
        )
    return grouped


def _render(filename: str, rows: list[dict[str, str]]) -> str:
    acceptance_id = rows[0]["acceptance_id"]
    rubric_ids = [r["rubric_id"] for r in rows]
    return HEADER_TEMPLATE.format(acceptance_id=acceptance_id, rubric_ids=rubric_ids)


def _format(content: str) -> str:
    """Format generated source with black, matching pyproject.toml exactly.

    Used for both write and --check so the two modes compare the identical
    transform. Raises (rather than silently falling back to unformatted
    content) if black is broken — a swallowed formatting failure would make
    --check misreport a toolchain problem as CSV drift.
    """
    return format_str(content, mode=BLACK_MODE)


def generate(check: bool = False) -> int:
    rows = _read_llm_rows()
    if len(rows) != 60:
        print(f"expected 60 LLM rows, found {len(rows)}", file=sys.stderr)
        return 2
    grouped = _group_by_file(rows)
    if len(grouped) != 20:
        print(f"expected 20 target files, found {len(grouped)}", file=sys.stderr)
        return 2

    planned = {
        "__init__.py": '"""Generated Phase 2 LLM requirement contract tests."""\n',
        "conftest.py": _format(CONFTEST_CONTENT),
    }
    for filename, file_rows in sorted(grouped.items()):
        planned[filename] = _format(_render(filename, file_rows))

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    stale: list[str] = []
    for filename, content in planned.items():
        path = OUT_DIR / filename
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current != content:
            stale.append(filename)
            if not check:
                path.write_text(content, encoding="utf-8")

    if check:
        if stale:
            print(f"stale/missing: {stale}", file=sys.stderr)
            return 1
        print("✅ requirement tests are up to date with the rubric matrix.")
        return 0

    print(f"✅ wrote {len(planned)} file(s) to {OUT_DIR.relative_to(REPO_ROOT)}/")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="exit 1 if generated files are stale")
    args = parser.parse_args(argv)
    return generate(check=args.check)


if __name__ == "__main__":
    sys.exit(main())
